version: '3.8'

services:
  c-benchmarks:
    build:
      context: .
      dockerfile: c/Dockerfile
    container_name: c_benchmarks
    volumes:
      - shared-data:/usr/src/app/bin

  checked-c-benchmarks:
    build:
      context: .
      dockerfile: checked-c/Dockerfile
    container_name: checked_c_benchmarks
    volumes:
      - shared-data:/usr/src/app/bin

  analysis:
    build:
      context: .
      dockerfile: analysis/Dockerfile
    container_name: analysis
    volumes:
      - shared-data:/usr/src/app/bin
    depends_on:
      - c-benchmarks
      - checked-c-benchmarks

volumes:
  shared-data: